### PR TITLE
spec file: Add configuration migration.

### PR DESCRIPTION
**Pull request by hramrach**

### CODE REVIEW

**Comment by hramrach** [comment]
Seems to be working.

Should I send this to a mailing list?

**Comment by djbw** [comment]
> Seems to be working.
> 
> Should I send this to a mailing list?

Yes, please. Thank you for digging into this. And if sending to the mailing list is a burden let us know and we'll send it for you.

**Comment by hramrach** [comment]
I tried but I don't see it in the archives. Is the nvdimm list subscriber-only?

**Comment by stellarhopper** [comment]
@hramrach hm, it shouldn't be.. Did you use nvdimm@lists.linux.dev ?

**Comment by hramrach** [comment]
Looks like I cannot post to that list for some reason. Resending does not help.

**Comment by stellarhopper** [comment]
Applied manually to pending, will be in v73

**Pull request closed without merging**
